server:
  port: 8104
  servlet:
    context-path: /api/plan
spring:
  application:
    name: fyp-backend-plan-service
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        service: fyp-backend-plan-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fyp.qian.planservice.controller

knife4j:
  enable: true