server:
  port: 8102
  servlet:
    context-path: /api/user
spring:
  application:
    name: fyp-backend-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manchester_exploration?useSSL=false&serverTimezone=GMT
    username: root
    password: q9I3a2N7
  session:
    timeout: 86400
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        service: fyp-backend-user-service

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delete_state
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fyp.qian.userservice.controller
knife4j:
  enable: true